# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAgregarNota():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_agregarNota(self):
    self.driver.get("http://localhost:5173/")
    self.driver.set_window_size(1552, 832)
    self.vars["antes"] = len(self.driver.find_elements(By.XPATH, "//table/tbody/tr"))
    self.driver.find_element(By.CSS_SELECTOR, "input").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").send_keys("nota sel ide1")
    self.driver.find_element(By.CSS_SELECTOR, "textarea").click()
    self.driver.find_element(By.CSS_SELECTOR, "textarea").send_keys("cuerpo nota 1")
    self.driver.find_element(By.CSS_SELECTOR, "select").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, "select")
    dropdown.find_element(By.XPATH, "//option[. = 'Alta']").click()
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(4)").click()
    self.vars["despues"] = len(self.driver.find_elements(By.XPATH, "//table/tbody/tr"))
    self.vars["rowsIncreased"] = self.driver.execute_script("return Number(arguments[0]) < Number(arguments[1]);", self.vars["antes"],self.vars["despues"])
    assert(self.vars["rowsIncreased"] == True)
  
